### ISSUE TITLE
Why graph algorithm or Mesh is not popular applying for 3D non-Euclidean structured data?

### ISSUE THREAD

**Issue by shangguan91** [nicolas-chaulet/torch-points3d#372]

**Comment by tchaton** [comment]
Hey @shangguan91,

I guess because the mesh tends to densify their triangles when the surface starts to be complicated.
Therefore, convolution on mesh can be less expressive than convolution on pointcloud sampled on a grid.
Also, most of data acquisition comes directly in the form of pointcloud, and therefore pointcloud methods are developing faster.

Best regards,
Thomas Chaton.
