### ISSUE TITLE
What is full_res in tracker options?

### ISSUE THREAD

**Issue by cvjimmy0704** [nicolas-chaulet/torch-points3d#412]
Hi, 
Thanks for the great work. When we used do part segmentation task, what does the "full_res" do when running eval.py? I know it will output different iou metrics, but could not find the definition.
J

**Comment by tchaton** [comment]
Dear @cvjimmy0704,

Some transforms as GridSampling or FixedPoints removed points from the pointcloud. Full_res active the logic to make prediction / interpolation over the raw_data, providing the real metrics.

Best regards,
T.C

**Comment by cvjimmy0704** [comment]
Thank you for your answer @tchaton, 

So if I want to have predictions for all the points by the trained model (NOT predictions on  some points then do interpolation), I just need to turn off test_transforms (GridSampling or FixedPoints) in and probably set batch_size=1?

Is Full_res activated if we run forward.py? 
Bests,
J

**Comment by tchaton** [comment]
Hey @cvjimmy0704,

Not that won't work out. If you trained with gridSampling, you need to make inference with gridSampling.

We support full_res for ShapeNet, Scannet, S3dis. Read the code, it will help you understand.

The technique for full res is pretty simple:

1. Tag points: SaveOriginalPosId    # Required so that one can recover the original point in the fused point cloud before applying any point reduction.

2. Do any kind of transform.

3. During process() in the dataset, we save the raw_data + processed_data (applied pre_transform). Expect s3disfused which needs to be fused as raw_data
  In the tracker, we create an array counter + prob predictions and use the SaveOriginalPosId to populate those arrays.
  When the full test set  (+ voting if activated) has been forwarded, we use interpolation_knn 1 to extrapolate predictions to raw_data.

4 . You get full res predictions !

Example s3dis: https://github.com/nicolas-chaulet/torch-points3d/blob/2f2aa10896504ea5e72585a5dbfa364ff6d018e6/torch_points3d/datasets/segmentation/s3dis.py#L466

Example Tracker: https://github.com/nicolas-chaulet/torch-points3d/blob/2f2aa10896504ea5e72585a5dbfa364ff6d018e6/torch_points3d/metrics/s3dis_tracker.py#L84
