### ISSUE TITLE
KPConv is very slow

### ISSUE THREAD

**Issue by VitorGuizilini-TRI** [nicolas-chaulet/torch-points3d#424]
Hi, thank you for the great repository, it will be very helpful on my projects. I am trying to use KPConv, but the forward pass is very slow, this is a snippet:

```
import time

import numpy as np
import torch
from torch_geometric.data import Batch, Data
from torch_points3d.applications.kpconv import KPConv

input_nc = 0
batch_size = 3
num_points_per_sample = [10000, 8000, 6700]
num_classes = 10

print(torch.cuda.is_available())

model = KPConv(
    architecture="unet",
    input_nc=input_nc,
    output_nc=num_classes,
    num_layers=4,
)
model = model.cuda()

samples = []
for idx_batch in range(batch_size):
    nb_points = num_points_per_sample[idx_batch]
    pos = torch.randn((nb_points, 3)).cuda()
    y = torch.from_numpy(np.random.choice(range(num_classes), nb_points)).cuda()
    x = torch.ones((nb_points, 1)).cuda()
    samples.append(Data(pos=pos, x=x))
data = Batch.from_data_list(samples)

optim = torch.optim.Adam(model.parameters(), lr=0.0001)

for i in range(1000):
    st = time.time()
    output = model.forward(data)
    print(time.time() - st)
```

It takes around 0.6 seconds for the forward pass, is that normal?

**Comment by humanpose1** [comment]
I think It's because to apply KPConv, we need to perform radius search on each points. 
In your case, KPConv computes neighbors and sampling on the fly (on GPU) using a bruteforce search which is quite slow.  

If you want to compute multiscale using cpu, please have a look at this transform
```python
from torch_points3d.core.data_transform import MultiScaleTransform
strategies = model.get_spatial_ops()
transform = MultiScaleTransform(strategies)
data = transform(data)
```

please also have a look at this notebook of [KPConv shapenetPart](https://github.com/nicolas-chaulet/torch-points3d/blob/master/notebooks/PartSegmentationKPConv.ipynb)). In the notebook, when we create the dataloader, you can see that the argument precompute_multiscale is set to True. It's because, in the dataloader, there is an option to precompute the neighbors on cpu. and we apply `MultiScaleTransform`. 
I hope it's clearer now.

**Comment by VitorGuizilini-TRI** [comment]
Thank you, it's clearer now. However, I am planning to apply KPConvs to pointclouds that change over time, so I think that method won't work for my application after all.

**Comment by nicolas-chaulet** [comment]
I think it should work, the transform is applied every time a new point cloud is loaded.

**Comment by VitorGuizilini-TRI** [comment]
The pointclouds are produced in pytorch though, by lifting image information with depth, so bringing it back to the CPU for the transform would be very costly as well. Is there any way around that?

**Comment by nicolas-chaulet** [comment]
If you are doing that in a data loader then I would say that it still worth it (done in paralel with the forward pass on GPU) but if you have an end to end model where point clouds are generated by a first model then yes you are right it would not help.
