### ISSUE TITLE
On latency computations and logging to TensorBoard

### ISSUE THREAD

**Issue by chaitjo** [nicolas-chaulet/torch-points3d#522]
Hi, I had a quick Q. on a related note as #417 on computing performance measures: in the tracker during training, we are computing the latency for data loading and iteration, which is very useful. 

What would be the best approach to logging these statistics or their per-epoch average into Tensorboard?

I would also be interested in logging additional performance statistics such as GPU usage and MACs/FLOPs. I will be attempting to utilize https://github.com/Lyken17/pytorch-OpCounter. I wonder if you already tried it, though?

**Comment by nicolas-chaulet** [comment]
Hi! You could modify the tracker to track custom metrics in addition to the model's metrics (add something like a track_values methods to the base tracker) and then change the publish method so that it returns your additional metrics. The publishing to tensorboard or wandb will be taken care off for you.

Regarding GPU usage, wandb supports that out of the box and for OP Counter you can try that but basically I think you will have to count the number of operations for each module in the code before using it.
