### ISSUE TITLE
On GPU usage of MESSAGE_PASSING vs. DENSE formats

### ISSUE THREAD

**Issue by chaitjo** [nicolas-chaulet/torch-points3d#525]
Hello, I see than many point-based methods can be implemented via both message passing and dense convolution formats, as specified in the documentation, too: https://torch-points3d.readthedocs.io/en/latest/src/advanced.html#data-formats-for-point-cloud

However, I found that the message passing format consumes **significantly larger amount of GPU memory**. E.g. on ShapeNet for PointNet++, `pointnet2ms` (MP) takes 7-8 GB compared to `pointnet2_largemsg` (DENSE) taking 3-4 GB on my hardware, keeping all else equal in terms of training settings. Similarly, on S3DIS, I am only able to use the PointNet++ variants; the MP variants run out of memory. In terms of inference speed, I again found the DENSE format to be faster.

Coming from a Graph NNs background, this seems unintuitive: libraries such as PyTorch Geometric were developed to facilitate faster message-passing operations and overcome the bottlenecks of memory/speed that using dense formats was leading to. 

Are the MP implementations of models behaving as expected, or could there be some issues here? In what case/for which model would I want to use the MP format over DENSE formats?

**Comment by nicolas-chaulet** [comment]
This was probably the first thing we discovered with @tchaton . Using the Dense format is much more efficient because you can rely on the super optimised classic convolution operators. Pytorch Geometric is very optimised for graph data but indeed is still a bit slower and uses more memory than using a dense memory representation. 

I cannot tell you exactly why but it seems intuitive to me that having Dense data (which is very structured) is more efficient than using a message passing format which maintains a graph of neighbours and can handle unstructured data but at the cost of less optimised operations.

**Comment by chaitjo** [comment]
I see, thank you for the insight!
