### ISSUE TITLE
Sparse convolution backend

### ISSUE THREAD

**Issue by victoryc** [nicolas-chaulet/torch-points3d#560]
Does anybody know whether there are any advantages to using MinkowskiEngine as the backend relative to the SparseConvNet library (from Facebook Research), as far 3D convolutions are concerned? 

Thanks!

**Comment by CCInc** [comment]
I am thinking the primary difference will be speed of the backends. There are some benchmark results here https://nvidia.github.io/MinkowskiEngine/benchmark.html and MinkowskiEngine has since been updated to be faster. In any case, this library doesn't currently support SparseConvNet. In addition, I think minkowskiengine and torchsparse from the MIT-HAN-LAB will be updated more frequently than sparseconvnet.
