### ISSUE TITLE
Cannot use "pointgroup-scannet" from the PretrainedRegistry

### ISSUE THREAD

**Issue by gabrieleangeletti** [nicolas-chaulet/torch-points3d#597]
When I try to use this model from the registry:

    model = PretainedRegistry.from_pretrained("pointgroup-scannet")

I get the following error: `TypeError: '>' not supported between instances of 'int' and 'NoneType'` in `torch_points3d/utils/model_building_utils/model_definition_resolver.py` line 10: `"FEAT": max(dataset.feature_dimension, 0),`.

I'm guessing this is because this model has got an empty dictionary in `pretrained_api.MOCK_USED_PROPERTIES`. Is this model supposed to be used with `mock_dataset=False` only?

**Comment by nicolas-chaulet** [comment]
Hi,
It's been a while since we haven't re trained that one and it is probably outdated now... Also, we never managed to achieve the same performances as the original paper. Close but not quite the same. Probably some issue related to how we voxelise data, they treat the point clouds in their full resolution.

**Comment by gabrieleangeletti** [comment]
Ok thank you for the info, I'll close this then.

**Comment by jaswanthbjk** [comment]
The reason might be that the model-parameters used for training is very different from the one proposed in the paper.

1. number of points perscene is 100000 in the model here and 250000 in the paper. 
2. Minimum voxel size is 0.02 proposed in the paper while it is 0.05 here. 
3. the cluster-radius is 0.075 in the current model while it's is 0.03 in the paper
