### ISSUE TITLE
Landmark Detection in CT scans

### ISSUE THREAD

**Issue by m-ali-awan** [nicolas-chaulet/torch-points3d#701]
Hi there, hope all of you are fine.
I am working on landmark detection in CT scans, and I am not able to find any useful resources or some work that I can extend. So do we have any such resources in MedicalNet, Torch3D, or any other related library?
I also explored torch-points3d, but couldn't find related work.
I found the wonderful blog on how to use PyTorchLightning along with Rising for 3D segmentation, wondering if someone has also worked on landmark detection..
Kindly do share it here..
Thanks,
Best Regards,
Muhammad Ali

**Comment by metazool** [comment]
Hi @m-ali-awan, hope you're well too. The issues here are intended for bug reports and feature contributions for `torch-points3d` rather than more general questions about applied research problems. These paper implementations look more relevant to your interesting problem:

[A tool for accurately placing 3D landmarks on 3D facial scans](https://github.com/RasmusRPaulsen/Deep-MVLM)
[A novel communicative multi-agent reinforcement learning (C-MARL) system to automatically detect landmarks in 3D medical images](https://github.com/gml16/rl-medical)

There's also a Slack community for Pytorch-Geometric [linked from here](https://pythonrepo.com/repo/rusty1s-pytorch_geometric-python-deep-learning) but again, that discussion focuses on research and development on methods, rather than applications.

Good luck!

**Comment by m-ali-awan** [comment]
Thanks a lot, @metazool, and sorry for my query.
But I am not able to find any related community, also the slack link is not working.

Again, thanks a lot, and I apologize for the wrongly placed query.

**Comment by nicolas-chaulet** [comment]
Hey @m-ali-awan this would be a working link to access Slack, you can also find it in the README. 
https://join.slack.com/t/torchgeometricco/shared_invite/zt-p6br3yuo-BxRoe36OHHLF6jYU8xHtBA

Alternatively, feel free to use the discussion section of Github and let's take it from there!

**Comment by m-ali-awan** [comment]
Hi Nicolas,Thanks a lot! Sent from Mail for Windows From: Nicolas ChauletSent: Monday, December 13, 2021 2:31 PMTo: nicolas-chaulet/torch-points3dCc: Muhammad Ali; MentionSubject: Re: [nicolas-chaulet/torch-points3d] Landmark Detection in CT scans (Issue #701) Hey @m-ali-awan this would be a working link to access Slack, you can also find it in the README.https://join.slack.com/t/torchgeometricco/shared_invite/zt-p6br3yuo-BxRoe36OHHLF6jYU8xHtBAAlternatively, feel free to use the discussion section of Github and let's take it from there!—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
